# Generated by Django 4.1.1 on 2022-11-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='typeuser',
            field=models.BooleanField(default=False),
        ),
    ]
