# Generated by Django 4.0.6 on 2022-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_delete_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='local',
            field=models.CharField(max_length=10),
        ),
    ]
