# Generated by Django 4.1.1 on 2022-11-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_typeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='typeuser',
        ),
    ]
