# Generated by Django 4.0.6 on 2022-08-27 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tag_hora_alter_tag_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
