# Generated by Django 4.1.1 on 2022-11-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("core", "0004_usuario_typeuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachorro",
            name="tel_responsavel",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                default="media_files/semfoto.png",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="media.image",
            ),
        ),
    ]
