# Generated by Django 4.0.6 on 2022-08-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrolocais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrolocais',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='local',
        ),
    ]
