# Generated by Django 4.1 on 2022-08-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_registrolocais_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedouro',
            name='hardware',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
