# Generated by Django 4.1.1 on 2022-12-05 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_comentarios_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
