# Generated by Django 4.1.1 on 2022-12-05 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('core', '0009_comentarios_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='foto',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.image'),
        ),
    ]
