# Generated by Django 4.1 on 2022-08-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_publicacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacoes',
            name='publicado',
        ),
    ]
