# Generated by Django 4.1 on 2022-08-28 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_publicacoes_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacoes',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
