# Generated by Django 4.1 on 2022-08-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_publicacoes_publicado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
