# Generated by Django 4.1.1 on 2022-10-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('core', '0014_comentarios_alter_publicacoes_autor_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.image'),
        ),
    ]
