# Generated by Django 4.1.1 on 2022-10-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_cachorro_foto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentarios",
            old_name="comentario",
            new_name="texto",
        ),
    ]
