# Generated by Django 4.1.1 on 2022-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_comentario_comentarios_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='altura',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cachorro',
            name='peso',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
