# Generated by Django 4.1.1 on 2022-10-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cachorro_altura_alter_cachorro_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='nome_responsavel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='tel_responsavel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
