# Generated by Django 4.1.1 on 2022-10-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cachorro_nome_responsavel_cachorro_tel_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
    ]
