# Generated by Django 4.1.1 on 2022-10-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cachorro_castrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='tel_responsavel',
            field=models.URLField(default=''),
        ),
    ]
